#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 100.25.198.23

    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
